version: '3'
services:
  go-greenhouse-gpio:
    build: .
    image: docker.io/noodlensk/go-greenhouse-gpio
    privileged: true
    restart: on-failure
    volumes:
      - "./config.yaml:/config.yaml"
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    